name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    uses: TeamFelnull/actions-reusable-workflows/.github/workflows/mcmod-release.yml@master
    with:
      build_tasks: "build curseforge modrinth publish"
    secrets:
      curseforge_token: ${{ secrets.CURSEFORGE_TOKEN_MORI }}
      modrinth_token: ${{ secrets.MODRINTH_TOKEN_MORI }}
      maven_password: ${{ secrets.MAVEN_PASSWORD }}

  postRelease:
    name: Update after release
    needs: release
    uses: TeamFelnull/actions-reusable-workflows/.github/workflows/mcmod-post-release.yml@master
    with:
      update_forge_version_check: false
      update_neoforge_version_check: false